import Image from "next/image";

const about = () => {
  return (
    <div>
      <img
        className="slides"
        src="/slides/Slide_1.png"
        alt="logo"
        layout="fill"
        objectFit="contain"
      />
      <img
        className="slides"
        src="/slides/Slide_2.png"
        alt="logo"
        layout="fill"
        objectFit="contain"
      />
      <img
        className="slides"
        src="/slides/Slide_3.png"
        alt="logo"
        layout="fill"
        objectFit="contain"
      />
      <img
        className="slides"
        src="/slides/Slide_4.png"
        alt="logo"
        layout="fill"
        objectFit="contain"
      />
      <img
        className="slides"
        src="/slides/Slide_5.png"
        alt="logo"
        layout="fill"
        objectFit="contain"
      />
      <img
        className="slides"
        src="/slides/Slide_6.png"
        alt="logo"
        layout="fill"
        objectFit="contain"
      />
      <img
        className="slides"
        src="/slides/Slide_7.png"
        alt="logo"
        layout="fill"
        objectFit="contain"
      />
      <img
        className="slides"
        src="/slides/Slide_8.png"
        alt="logo"
        layout="fill"
        objectFit="contain"
      />
      <img
        className="slides"
        src="/slides/Slide_9.png"
        alt="logo"
        layout="fill"
        objectFit="contain"
      />
      <img
        className="slides"
        src="/slides/other_slide.png"
        alt="logo"
        layout="fill"
        objectFit="contain"
      />
      <img
        className="slides"
        src="/slides/Slide_10.png"
        alt="logo"
        layout="fill"
        objectFit="contain"
      />
    </div>
  );
};

export default about;
